disabled_rules: # rule identifiers to exclude from running
    - line_length
    - todo
    - identifier_name
    - type_name
    - force_try
    - vertical_whitespace
opt_in_rules:
    - empty_count
excluded:
    - Carthage
